name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --only test

      - name: Run black
        run: poetry run black --check --line-length 120 .

      - name: Run flake8
        run: poetry run flake8 --max-line-length 120 --ignore "E203,E501,W503" .

      - name: Run isort
        run: poetry run isort --check-only --diff --profile black .

      - name: Run mypy
        run: poetry run mypy --ignore-missing-imports .
